### ISSUE TITLE
content broken

### ISSUE THREAD

**Issue by eexpress** [maoschanz/gedit-plugin-markdown_preview#12]
Some preview contents disappear or format is wrong.

eg: entire "### showsvgpngtxt" part which with a table, "### ~/.config/showit.fontname.list" part and more.

syntax compatibility issues??
 
![屏幕截图](https://user-images.githubusercontent.com/700793/68179417-bebc5100-ffca-11e9-89a4-3d624dfab212.png)

**Comment by maoschanz** [comment]
I think it's because of pandoc. This plugin has 2 possible ways to render markdown:

- with `python3-markdown`, which is not very powerful but follows more closely the standard you're using
- with `pandoc`, which can export the preview to a lot of useful file formats, and render .tex files too. But pandoc expect a new empty line after a `---` (pandoc also expect empty lines in several other situations, around lists for example)

If `python3-markdown` is installed on your system, you should be able to select it in the plugin options 
![Capture d’écran de 2019-11-05 13-14-06](https://user-images.githubusercontent.com/19996113/68207063-6a1ad500-ffce-11e9-9bc9-ef87bd9bfc13.png)

If you prefer the more powerful pandoc rendering you have to add empty new lines

**Comment by maoschanz** [comment]
Since this plugin is still not finished and released yet, i don't know what features are available in the version you use, if you can't change the renderer like me you may need to reinstall from a newer commit

**Comment by eexpress** [comment]
> expect a new empty line after a ---

Sure, I follow this rule. Thanks.
